# Generated by Django 5.1 on 2024-09-28 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French')], default='EN', max_length=10), null=True, size=None),
        ),
    ]
