# Generated by Django 5.1 on 2024-09-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
    ]
