# Generated by Django 5.1 on 2024-09-28 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish')], max_length=10), default=list, size=None),
        ),
    ]
