# Generated by Django 5.1 on 2024-09-28 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish')], max_length=10), default=['E', 'N'], size=None, unique=True),
        ),
    ]
