# Generated by Django 5.1 on 2024-09-28 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish')], default='EN', max_length=10), size=None, unique=True),
        ),
    ]
