# Generated by Django 5.1 on 2024-09-28 20:30

import core.constants
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish')], max_length=10), default=core.constants.LANGUAGES.default_language, size=None),
        ),
    ]
