# Generated by Django 5.1 on 2024-08-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyimage",
            old_name="propertie",
            new_name="property",
        ),
    ]
