# Generated by Django 5.1 on 2024-08-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_rename_propertie_propertyimage_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="properties.collection",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collection",
            name="featured_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="properties.property",
            ),
        ),
    ]
