# Generated by Django 5.1 on 2024-09-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_category_collection_image_property_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="properties.category",
            ),
            preserve_default=False,
        ),
    ]
