# Generated by Django 5.1 on 2024-09-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_collection_host_property_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="properties.category",
            ),
        ),
    ]
