# Generated by Django 5.1 on 2024-09-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="name",
            new_name="reviewer_name",
        ),
    ]
