# Generated by Django 5.1 on 2024-09-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_rename_name_review_reviewer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
