# Generated by Django 5.1 on 2024-09-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_member_user_profile_delete_address_and_more"),
        ("properties", "0011_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core.profile",
            ),
            preserve_default=False,
        ),
    ]
