# Generated by Django 5.1 on 2024-09-08 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_review_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="availability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="from_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="number_of_guests",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="to_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
